apiVersion: v1
kind: Service
metadata:
  labels:
    app: codeinnovate
  name: codeinnovate
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    app: codeinnovate
